title: fahim-a-siddiqui.github.io
email: fahimsiddiqui717@gmail.com
description: >-
  A home for my writings. I like to write whatever's on my mind so nothing here is organized much. Everything here is from a hobbyist; don't expect anything grand.  
baseurl: ""
url: "https://fahim-a-siddiqui.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter 
